### ISSUE TITLE
Universe-2024.4.0 fails to install

### ISSUE THREAD

**Issue by Cetartiodactyla** [autopkg/foigus-recipes#151] opened 2024-08-09 11:18 UTC
Something changed on the latest package installer of Universe version 2024.4.0. There is no `install.sh` and so the postinstall-script fails :(

**Comment by foigus** [comment] 2024-08-09 12:15
It turns out I'm no longer a customer of Maxon/Red Giant, so I don't really have a standing to submit a support ticket.  Can you ask Maxon what their replacement is for silent/unattended installations, replacing `install.sh`?  Similar to what exists here:

https://support.maxon.net/hc/en-us/articles/4687177301788-Scripted-Install-Instructions

I'm not doing anything special to the software except automating the creation of a package that calls Maxon's scripts.

**Comment by Cetartiodactyla** [comment] 2024-08-09 14:11
Right, this is the string for the postinstall-script. Thanks for pointing me in the right direction!

```
<string>#!/bin/bash

# Determine working directory
install_dir=`dirname $0`

# Install Maxon App Installer using the script from the resources directory
# Maxon documentation here: https://support.maxon.net/hc/en-us/articles/4687177301788-Running-Scripted-Installers
"${install_dir}/Universe.app/Contents/MacOS/installbuilder.sh" --mode unattended --unattendedmodeui none %INSTALL_OPTIONS%</string>
```

Unfortunately their script still exits non zero, so the receipt is not written. I added `exit 0` to the postinstall-script, which, of course is a bad solution.

**Comment by foigus** [comment] 2024-08-10 02:39
I'd encourage checking to see whether the installation script exits 0 when simply run from Terminal, rather than when running underneath the installer environment in a `postinstall` script.  But If Maxon's install script isn't exiting 0 that's likely something Maxon themselves needs to take a look at.

I also don't know if `%INSTALL_OPTIONS%` (which was added to the Maxon App recipe to support the `skipMaxonAppGui` flag) makes sense here.

**Comment by foigus** [comment] 2024-08-10 02:58
Try adjusting the "FileCreator" processor in `Universe.pkg.recipe` to the following:

```
		<dict>
			<key>Arguments</key>
			<dict>
				<key>file_content</key>
				<string>#!/bin/bash

# Determine working directory
install_dir=`dirname $0`

# Install Universe using the script from the resources directory
"${install_dir}/Universe.app/Contents/MacOS/installbuilder.sh" --mode unattended --unattendedmodeui none</string>
				<key>file_mode</key>
				<string>0755</string>
				<key>file_path</key>
				<string>%RECIPE_CACHE_DIR%/Scripts/postinstall</string>
			</dict>
			<key>Processor</key>
			<string>FileCreator</string>
		</dict>
```

Regenerate the package and try again.  I can confirm a package created by AutoPkg with the above `FileCreator` processor will install successfully--but I'm a poor person to judge whether that installation of Universe is actually working.

**Comment by Cetartiodactyla** [comment] 2024-08-11 10:18
Works perfectly fine. Installs successfully and the receipt is written, thank you!

**Comment by foigus** [comment] 2024-08-11 13:17
Fixed by https://github.com/autopkg/foigus-recipes/commit/71c93548ae6020744d351672054245cec30b0395.  Thanks for testing!

**Closed by foigus** 2024-08-11 13:17 UTC
