### ISSUE TITLE
Maxon Universe PKG Install fails

### ISSUE THREAD

**Issue by Cetartiodactyla** [autopkg/foigus-recipes#98] opened 2022-06-23 13:35 UTC
While the postinstall script works just fine, the installer fails and the receipt is not written. Not sure what causes this.

**Comment by foigus** [comment] 2022-06-23 14:43
The issue is that the installation tool itself is exiting 1 for no discernible nor logged reason.  Running the "install.sh" script by hand from a downloaded copy of "Universe Installer.app" also exits 1--please file a ticket with Maxon and ask what's going on.

```
% sudo /Users/admin/Desktop/Universe\ Installer.app/Contents/Scripts/install.sh 
Password:

Running Red Giant installer tool rgdeploy
A log file for this install will be written here:
/Library/Logs/Red Giant/redgiant-installer-1655994774.log
...
1655994774 INFO deploy : running rgdeploy...
1655994774 DEBUG deploy : RG::Deploy::LoadValidationInfo
1655994774 INFO deploy : Parsing command-line rgdeploy args.
1655994774 INFO deploy : RG::DeployCLI::Run
rgdeploy version 2.1-d1 (full)
Copyright (c) 2021 Maxon Computer GmbH
Use of this software granted only under terms of Red Giant software license.
=====
1655994774 INFO deploy : RG::DeployCLI::DoDeployCommand
1655994774 INFO deploy : DeployPackagesFromDir: '/Users/admin/Desktop/Universe Installer.app/Contents/Scripts/../Resources/packages'  skip-count: 0 register: Yes skipMaxonAppGui: No
1655994774 INFO deploy : Checking packages to install...
1655994774 INFO deploy : ---------------------------
1655994774 INFO deploy : Installing from directory '"/Users/admin/Desktop/Universe Installer.app/Contents/Scripts/../Resources/packages"'
1655994774 INFO deploy : Located package com.redgiant.universe_text_av_club.zip
1655994774 INFO deploy : Located package com.redgiant.universe_transitions_unfold.zip
1655994774 INFO deploy : Located package com.redgiant.universe_stylize_carousel.zip
<snip>
1655994916 INFO deploy : Verifying installation...
1655994916 INFO deploy : Checking product dependencies
1655994916 INFO deploy : Checking product dependencies...
1655994916 INFO deploy : Completing installation.
1655994916 INFO deploy : DeployPackages: path-count: 0 register: Yes
1655994916 INFO deploy : No packages to deploy. no-op
1655994916 INFO deploy : DeployFileToDirectory: '"/Users/admin/Desktop/Universe Installer.app/Contents/Scripts/../Resources/packages/UniverseAcknowledgements.txt"' -> "/Library/Application Support/Red Giant/Documentation/Acknowledgements"
1655994916 INFO deploy : stashing existing file in case of rollback, from /Library/Application Support/Red Giant/Documentation/Acknowledgements/UniverseAcknowledgements.txt
1655994916 INFO deploy : Copy '/Users/admin/Desktop/Universe Installer.app/Contents/Scripts/../Resources/packages/UniverseAcknowledgements.txt' -> /Library/Application Support/Red Giant/Documentation/Acknowledgements
1655994916 INFO deploy : Installation complete.
1655994917 DEBUG deploy : Deleting rollback stash directory.
% echo $?
1

```

**Comment by floriangeyer** [comment] 2022-06-23 15:18
… exactly what I just found out. Thanks, I will ask Maxon about this.

**Comment by foigus** [comment] 2022-07-02 13:48
Universe 6.1 was released, can you update your copy of my repo and test?

**Comment by floriangeyer** [comment] 2022-07-03 11:02
Same thing, `install.sh` still exits `1`

**Comment by foigus** [comment] 2023-09-19 15:03
Closing this due to non-response.

**Closed by foigus** 2023-09-19 15:03 UTC
