### ISSUE TITLE
Color Navigator 7 doesn't open

### ISSUE THREAD

**Issue by paulc-us** [autopkg/foigus-recipes#126] opened 2023-09-19 13:28 UTC
For some reason, when I have munki install Color Navigator 7 from the autopkg recipe, it doesn't open.

**Comment by foigus** [comment] 2023-09-19 14:13
The only changes I make are:

- Unpacking the package, replacing the postinstall ([EIZO original](https://github.com/autopkg/foigus-recipes/blob/master/EIZO/Reference%20Scripts%20ColorNavigator7/Original%20EIZO%20Script/postinstall), [my edited version](https://github.com/autopkg/foigus-recipes/blob/master/EIZO/Reference%20Scripts%20ColorNavigator7/Fixed%20Script/postinstall)) to prevent ColorNavigator 7 from being launched at the end of the installation, and repacking the package
- This causes the package to become unsigned

I'm not making any material changes to EIZO's package itself.  My best suggestions would be A/B testing between various combinations of the following:
- The vanilla ColorNavigator 7 package from EIZO versus the package that's rebuilt by AutoPkg
- A new installation of ColorNavigator 7 versus an upgrade to an existing version of ColorNavigator 7
- Installation while a user is logged in versus when the computer is at the Login Window (note this will require removing the `RestartAction` in the Munki pkginfo)
- Installation by hand versus via Munki

**Comment by BitsDream** [comment] 2023-10-12 12:26
Same issue here. What I have tested so far:
- install AutoPKG package via Munki without logout -> CN doesn't start
- install AutoPKG package via Munki with require logout ->  CN doesn't start
- install AutoPKG package via Munki with require logout followed by manual reboot ->  CN doesn't start
- Manual install of AutoPKG package with user logged in -> CN doesn't start
- Manual install of original EIZO package -> CN starts

I compared the original and the AutoPKG package. The only difference I can find is the modified postinstall script and the fact that the repackaged installer is not signed. 
Access rights appear to be the same, postinstall script has execute rights. Everything appears to be OK.

**Comment by foigus** [comment] 2023-10-12 12:57
Additionally, please test by simply expanding (`pkgutil --expand`) and flattening (`pkgutil --flatten`) EIZO's original ColorNavigator 7 package.  That will remove the package signature without editing the `postinstall` script and at least help focus investigation between the two changes (`postinstall` change, package signature removal) caused by this recipe.

**Comment by foigus** [comment] 2023-10-12 13:04
Also please test by installing via a SSH session when a user is not logged in.

**Comment by poundbangbash** [comment] 2023-10-12 14:05
I have ColorNavigator 7 7.1.11 in Munki from an autopkg run.
I assigned it to a machine running Sonoma here and post-install ColorNavigator launches.  The initial launch took a good 4-5 seconds for anything in the GUI to appear, but it did launch fine.

**Comment by BitsDream** [comment] 2023-10-12 14:08
ColorNavigator 7 doesn't launch at all. It is visible for a couple of seconds in Activity Monitor and then disappears.
Removing the signature doesn't break the installer. It installs and runs fine.
Installing via ssh doesn't change anything. CN does not start at all.

**Comment by BitsDream** [comment] 2023-10-12 14:24
ColorNavigator 7.1.11 created with the same recipe doesn't work for me in macOS Monterey 12.7 (on M1). This is strange.

**Comment by BitsDream** [comment] 2023-10-12 15:15
It's probably not an issue of the recipes. I [rewrote](https://github.com/SRGSSR/recipes/tree/master/EIZO) them to just package the plain installer from EIZO. And after install ColorNavigator doesn't start.

**Comment by foigus** [comment] 2023-11-16 20:25
Closing since I'm unable to reproduce.

**Closed by foigus** 2023-11-16 20:25 UTC
